/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ClickMintGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "FEE_EACH_BPS"
      | "MAX_CLICKS_PER_BLOCK"
      | "MIN_POT_CLICKS"
      | "RESET_BUFFER"
      | "baseClickReward"
      | "click"
      | "clickCostCredits"
      | "clickPerEthWei"
      | "clickToken"
      | "clicksInHour"
      | "credits"
      | "currentPotEth"
      | "deposit"
      | "finalizeHour"
      | "gameHour"
      | "hourFinalized"
      | "hourPayout"
      | "hourWinWindow"
      | "hourWinner"
      | "owner"
      | "ownerSweepPotCarry"
      | "potCarry"
      | "potEthByHour"
      | "renounceOwnership"
      | "secretWallet"
      | "setAddresses"
      | "setEconomy"
      | "transferOwnership"
      | "treasury"
      | "utcWindow"
      | "windowMask"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressesUpdated"
      | "Clicked"
      | "Deposited"
      | "OwnershipTransferred"
      | "PotWin"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FEE_EACH_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CLICKS_PER_BLOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_POT_CLICKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESET_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseClickReward",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "click", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "clickCostCredits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clickPerEthWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clickToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clicksInHour",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPotEth",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeHour",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameHour",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hourFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hourPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hourWinWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hourWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerSweepPotCarry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "potCarry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "potEthByHour",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "secretWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEconomy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "utcWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "windowMask",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FEE_EACH_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CLICKS_PER_BLOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_POT_CLICKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESET_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseClickReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "click", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clickCostCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clickPerEthWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clickToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clicksInHour",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "credits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPotEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeHour",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameHour", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hourFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hourPayout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hourWinWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hourWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerSweepPotCarry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "potCarry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "potEthByHour",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secretWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEconomy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "utcWindow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "windowMask", data: BytesLike): Result;
}

export namespace AddressesUpdatedEvent {
  export type InputTuple = [treasury: AddressLike, secret: AddressLike];
  export type OutputTuple = [treasury: string, secret: string];
  export interface OutputObject {
    treasury: string;
    secret: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClickedEvent {
  export type InputTuple = [
    user: AddressLike,
    hourId: BigNumberish,
    totalForUserHour: BigNumberish,
    window: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    hourId: bigint,
    totalForUserHour: bigint,
    window: bigint
  ];
  export interface OutputObject {
    user: string;
    hourId: bigint;
    totalForUserHour: bigint;
    window: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    ethIn: BigNumberish,
    creditsOut: BigNumberish
  ];
  export type OutputTuple = [user: string, ethIn: bigint, creditsOut: bigint];
  export interface OutputObject {
    user: string;
    ethIn: bigint;
    creditsOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PotWinEvent {
  export type InputTuple = [
    hourId: BigNumberish,
    winner: AddressLike,
    clickPayout: BigNumberish,
    window: BigNumberish,
    entropy: BytesLike
  ];
  export type OutputTuple = [
    hourId: bigint,
    winner: string,
    clickPayout: bigint,
    window: bigint,
    entropy: string
  ];
  export interface OutputObject {
    hourId: bigint;
    winner: string;
    clickPayout: bigint;
    window: bigint;
    entropy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClickMintGame extends BaseContract {
  connect(runner?: ContractRunner | null): ClickMintGame;
  waitForDeployment(): Promise<this>;

  interface: ClickMintGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  FEE_EACH_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_CLICKS_PER_BLOCK: TypedContractMethod<[], [bigint], "view">;

  MIN_POT_CLICKS: TypedContractMethod<[], [bigint], "view">;

  RESET_BUFFER: TypedContractMethod<[], [bigint], "view">;

  baseClickReward: TypedContractMethod<[], [bigint], "view">;

  click: TypedContractMethod<[], [void], "nonpayable">;

  clickCostCredits: TypedContractMethod<[], [bigint], "view">;

  clickPerEthWei: TypedContractMethod<[], [bigint], "view">;

  clickToken: TypedContractMethod<[], [string], "view">;

  clicksInHour: TypedContractMethod<
    [hourId: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  credits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  currentPotEth: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  finalizeHour: TypedContractMethod<
    [hourId: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameHour: TypedContractMethod<[ts: BigNumberish], [bigint], "view">;

  hourFinalized: TypedContractMethod<[hourId: BigNumberish], [boolean], "view">;

  hourPayout: TypedContractMethod<[hourId: BigNumberish], [bigint], "view">;

  hourWinWindow: TypedContractMethod<[hourId: BigNumberish], [bigint], "view">;

  hourWinner: TypedContractMethod<[hourId: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerSweepPotCarry: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  potCarry: TypedContractMethod<[], [bigint], "view">;

  potEthByHour: TypedContractMethod<[hourId: BigNumberish], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  secretWallet: TypedContractMethod<[], [string], "view">;

  setAddresses: TypedContractMethod<
    [treasury_: AddressLike, secretWallet_: AddressLike],
    [void],
    "nonpayable"
  >;

  setEconomy: TypedContractMethod<
    [
      clickPerEthWei_: BigNumberish,
      clickCostCredits_: BigNumberish,
      baseClickReward_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  utcWindow: TypedContractMethod<[ts: BigNumberish], [bigint], "view">;

  windowMask: TypedContractMethod<
    [hourId: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_EACH_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CLICKS_PER_BLOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_POT_CLICKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESET_BUFFER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseClickReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "click"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clickCostCredits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "clickPerEthWei"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "clickToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "clicksInHour"
  ): TypedContractMethod<
    [hourId: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "credits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPotEth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "finalizeHour"
  ): TypedContractMethod<[hourId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameHour"
  ): TypedContractMethod<[ts: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hourFinalized"
  ): TypedContractMethod<[hourId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hourPayout"
  ): TypedContractMethod<[hourId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hourWinWindow"
  ): TypedContractMethod<[hourId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hourWinner"
  ): TypedContractMethod<[hourId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerSweepPotCarry"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "potCarry"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "potEthByHour"
  ): TypedContractMethod<[hourId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "secretWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAddresses"
  ): TypedContractMethod<
    [treasury_: AddressLike, secretWallet_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEconomy"
  ): TypedContractMethod<
    [
      clickPerEthWei_: BigNumberish,
      clickCostCredits_: BigNumberish,
      baseClickReward_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "utcWindow"
  ): TypedContractMethod<[ts: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "windowMask"
  ): TypedContractMethod<
    [hourId: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AddressesUpdated"
  ): TypedContractEvent<
    AddressesUpdatedEvent.InputTuple,
    AddressesUpdatedEvent.OutputTuple,
    AddressesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Clicked"
  ): TypedContractEvent<
    ClickedEvent.InputTuple,
    ClickedEvent.OutputTuple,
    ClickedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PotWin"
  ): TypedContractEvent<
    PotWinEvent.InputTuple,
    PotWinEvent.OutputTuple,
    PotWinEvent.OutputObject
  >;

  filters: {
    "AddressesUpdated(address,address)": TypedContractEvent<
      AddressesUpdatedEvent.InputTuple,
      AddressesUpdatedEvent.OutputTuple,
      AddressesUpdatedEvent.OutputObject
    >;
    AddressesUpdated: TypedContractEvent<
      AddressesUpdatedEvent.InputTuple,
      AddressesUpdatedEvent.OutputTuple,
      AddressesUpdatedEvent.OutputObject
    >;

    "Clicked(address,uint256,uint256,uint8)": TypedContractEvent<
      ClickedEvent.InputTuple,
      ClickedEvent.OutputTuple,
      ClickedEvent.OutputObject
    >;
    Clicked: TypedContractEvent<
      ClickedEvent.InputTuple,
      ClickedEvent.OutputTuple,
      ClickedEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PotWin(uint256,address,uint256,uint8,bytes32)": TypedContractEvent<
      PotWinEvent.InputTuple,
      PotWinEvent.OutputTuple,
      PotWinEvent.OutputObject
    >;
    PotWin: TypedContractEvent<
      PotWinEvent.InputTuple,
      PotWinEvent.OutputTuple,
      PotWinEvent.OutputObject
    >;
  };
}
