import { parseAbi } from "viem";

export const clickMintGameAbi = parseAbi([
  "function deposit() payable",
  "function depositFor(address player) payable",
  "function click()",
  "function clickFor(address player)",
  "function placeBet(uint8 slot) payable",
  "function setClickExecutor(address executor)",
  "function clickExecutor(address player) view returns (address)",
  "event ClickExecutorSet(address indexed player, address indexed executor)",
  "function clickToken() view returns (address)",
  "function clickCostCredits() view returns (uint256)",
  "function baseClickReward() view returns (uint256)",
  "function clicksPerHashTier() view returns (uint256)",
  "function minPotClicks() view returns (uint256)",
  "function totalClicksInRound(uint256 roundId) view returns (uint256)",
  "function credits(address user) view returns (uint256)",
  "function currentPotEth() view returns (uint256)",
  "function potCarry() view returns (uint256)",
  "function potEthByRound(uint256 roundId) view returns (uint256)",
  "function gameRound(uint256 ts) pure returns (uint256)",
  "function slotInRound(uint256 ts) pure returns (uint8)",
  "function roundWinner(uint256 roundId) view returns (address)",
  "function roundPayout(uint256 roundId) view returns (uint256)",
  "function roundFinalized(uint256 roundId) view returns (bool)",
  "function roundWinSlot(uint256 roundId) view returns (uint8)",
  "function blockBetDepositEthByRound(uint256 roundId) view returns (uint256)",
  "function BLOCK_BET_SLOT_COUNT() view returns (uint256)",
  "function totalBetOnSlot(uint256 roundId, uint8 slot) view returns (uint256)",
  "function totalBetsAllSlots(uint256 roundId) view returns (uint256[46])",
  "function userBetsAllSlots(uint256 roundId, address bettor) view returns (uint256[46])",
  "function userBetOnSlot(uint256 roundId, address user, uint8 slot) view returns (uint256)",
  "function blockBetCarry() view returns (uint256)",
  "function blockBetClaimableEth(address user) view returns (uint256)",
  "function claimBlockBetEth()",
  "function TROPHY_ROLL_DENOM() view returns (uint256)",
  "function trophyDropWeight() view returns (uint256)",
  "function setTrophyDropWeight(uint256 weight)",
  "function potKeeper() view returns (address)",
  "function setPotKeeper(address k)",
  "function finalizeRound(uint256 roundId)",
  "event Deposited(address indexed user, uint256 ethIn, uint256 creditsOut)",
  "event Clicked(address indexed user, uint256 roundId, uint256 totalForUserRound, uint8 slotInRound)",
  "event PotWin(uint256 indexed roundId, address indexed winner, uint256 ethPayout, uint8 winSlot, bytes32 entropy)",
  "event BlockBetPaid(uint256 indexed roundId, uint8 winSlot, uint256 totalPot, uint256 winnersPaid)",
  "event BlockBetCarried(uint256 indexed roundId, uint256 amount)",
  "event BlockBetEthClaimed(address indexed to, uint256 amount)",
]);

export const binaryTrophyAbi = parseAbi([
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event TrophyMinted(address indexed to, uint256 indexed tokenId, uint64 totalClicks, uint8 fragmentSlot, bool viaGame)",
  "function approve(address to, uint256 tokenId)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function tokenURI(uint256 tokenId) view returns (string)",
]);

export const escrowAbi = parseAbi([
  "function deposit(address token, uint256 tokenId, address beneficiary) returns (uint256)",
  "function claim(uint256 holdId)",
  "function nextHoldId() view returns (uint256)",
  "function holds(uint256 holdId) view returns (address token, uint256 tokenId, address depositor, address beneficiary, bool released)",
]);

export const clickTokenAbi = parseAbi([
  "function owner() view returns (address)",
  "function maxSupply() view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function game() view returns (address)",
  "function claimVested()",
  "function earlySpendPending(uint256 amount)",
  "function claimable(address account) view returns (uint256)",
  "function pendingVested(address account) view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function mintForTestingEnabled() view returns (bool)",
  "function mintForTesting(address to, uint256 amount)",
  "event TestingMint(address indexed to, uint256 amount)",
  "event InitialLpBootstrapMint(address indexed to, uint256 amount)",
]);
